# Blog info
blog_name: Sam's Blog
slogan: 山言两语

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/mountain_zh.ico

# For seo
keywords: 安卓,android,山言两语

init_page_content: HOME_NAV  # HOME_NAV |POST

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: About
    url: /about
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/samwangds
    target_blank: true #在新页面打开
  - name: JianShu
    url: http://www.jianshu.com/users/69e7a375ef62/latest_articles
    target_blank: true
  - name: WeiBo
    url: http://weibo.com/wds3jay
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于我
    url: /about/
    target_blank: false
#  - name: RSS
#    url: /atom.xml
#    target_blank: true # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT


# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

link:
  - name: hexo doc
    info: hexo 中文文档
    url: https://hexo.io/zh-cn/docs/index.html
    avatar: https://hexo.io/logo.svg?v=3&s=460

about:
  - type: me
    icon: icon-user
    text_value:
    - "汪东山 (Sam Wang)，1990.04"
    - "喜欢美的设计，擅长编程，死瘦宅."
    - "安卓开发工程师."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "samwangds"
    text_value_url: https://github.com/samwangds
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@你不是真正的悲伤"
    text_value_url: http://weibo.com/wds3jay
  - type: jianshu
    text_key: 简书
    text_value: "山言两语"
    text_value_url: http://www.jianshu.com/users/69e7a375ef62/latest_articles
  - type: mail
    text_key: Email
    text_value: "wds0405@qq.com"
  - type: location
    icon: icon-location
    text_value: 厦门

# Stats
google_analytics:
baidu_analytics: 19d10c44efe02c941e3ff1edb5a750c5

# Comment service
#disqus_shortname: forsigner
duoshuo_shortname: samwang
# Custom CSS style
# personal_style: /css/forsigner.css
